# Generated by Django 4.2.7 on 2023-11-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=20)),
                ('fecha_publicacion', models.DateField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
