# Generated by Django 4.2.7 on 2023-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_categoria_libro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
